import typing


class Unum:
    def __init__(self, val: float): ...

    def __str__(self) -> str: ...
    __repr__ = __str__

    def __mul__(self, other: Unum) -> Unum: ...
    @typing.overload
    def __mul__(self, other: float) -> Unum: ...
    __rmul__ = __mul__

    def __div__(self, other: Unum) -> Unum: ...
    @typing.overload
    def __div__(self, other: float) -> Unum: ...
    __truediv__ = __rdiv__ = __rtruediv__ = __div__


def add_unit(name: str, long_name: str) -> Unum: ...